# Базовые настройки
domain: "https://*.up.railway.app"
https_only: true
use_pubsub_feeds: false
check_tables: true

# Внешняя PostgreSQL (заменится через ENV в Railway)
db:
  dbname: "${DATABASE_NAME}"
  host: "${DATABASE_HOST}"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  port: "${DATABASE_PORT}"

# Порт внутри контейнера
port: 3000
host: "0.0.0.0"

# Качество по умолчанию
default_home: "Popular"
default_player_options:
  quality: "720p"
  speed: "1.0"

# Локализация
locale: "ru"
